# Env Options
sudo: required
dist: trusty

env:
  global:
    - PROJECT=pac-mule
    - DEB_DISTRO='stretch buster sid artful xenial'

# Language Options
language: go

go:
  - 1.9.4
  - "1.10"
  - "1.10.1"

before_install:
  - sudo apt-get update -qqy
  - sudo apt-get install -qqy upx tar golang-go dh-make devscripts dh-golang build-essential fakeroot subversion git

script:
  - go test ./... -race -args start -v

before_deploy:
  - sudo make clean
  - go get -u github.com/Debian/dh-make-golang
  - svn checkout https://github.com/junland/repo-packaging/trunk/pac-mule/debian
  - wget -O Makefile.pkgs https://raw.githubusercontent.com/junland/repo-packaging/master/Makefile
  - sed "s/DEB_DISTRO?=unstable/DEB_DISTRO?=$DEB_DISTRO/g" Makefile.pkgs
  - DEB_ARCH=amd64 make -f ./Makefile.pkgs deb
  - DEB_ARCH=armhf make -f ./Makefile.pkgs deb
  - sudo tar czf ./pac-mule-debs-$TRAVIS_TAG.tar.gz ../pac-mule-debs

deploy:
  provider: releases
  api_key:
    secure:     llTfOhB9+wlU0Y/AEVitdzQgFM07svqrcNqZA7xc/LPZd5LOl8GHrVTNICPpJe0fcTmKOKP9Ck6DsYm0QS9xV0DffMJM5EnCCJpP+vE83Lx7giTjnxCBbqsNhKuSJOJ6zbDwOlJRGMp3TRjAWw3myhXD5DVBGT5VG0lsXEoteShIVgGnonuT6qof09CFeoOAeLnEvbyS7oQkzg8BdnWQPdPO8I5PYKi+bbT85A6qKx5h9pRF2/XLHaqgVsTR56nO2og65Bj5J7+Oz0FUQVPUcMKVbu67noKys1+QqbmPp4kJRtrRiV1JD3gGthrZBtqCQ9lySQxSYaiAWsqWHOowg0qTtrlHmrmUoNnFLvtg94fFSvvUy8UEsvHilaoWM/2wTp1KyeHvUicVWCj2LAbUX58HLCXpkHyjMuqlf4xnxFNJCKLkhwWwTyQdlyXEB+EtjpKN/Slk7VX1Xfv/1lTaS2FFHPJbTdbGhqs1qzwcDjx4ezf6wNTKwevYS8ogbb1IYXvwnJCcjHEGdIyK9L5p69aV+ShQP18fdiMAXXqve54Q7wO072FPPpcwqmbIc8VDK8XqQ0KdvvS0IabY36Zh8OD8uBJLSMHaWsPylCL7gkIjfL8kYoCChmEdPDqlz65g/BdtR2q9mzWJ+ChOcYJNwTBlBORaIVdNeVjYoiur6to=
  file_glob:    true
  file:         ./pac-mule-debs-*.tar.gz
  skip_cleanup: true
  on:
    branch:     master
    go:         "1.10.1"
    tags:       true
    repo:       junland/pac-mule
