# Env Options
sudo: required
dist: xenial

env:
  global:
    - PROJECT=pac-mule

# Language Options
language: go

go:
  - 1.8.5
  - 1.9.3
  - 1.9.4
  - "1.10"
  - 1.10.1
  - master
  - tip

before_install:
  - sudo echo "deb http://archive.ubuntu.com/ubuntu/ bionic universe" >> /etc/apt/sources.list
  - sudo echo "deb http://archive.ubuntu.com/ubuntu/ bionic main restricted" >> /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install upx tar git gccgo
  - gccgo -v

before_script:
 - go get -t ./...

script:
  - go test ./utils -race -args start -v

before_deploy:
  - sudo make clean
  - VERSION=$TRAVIS_TAG make releases

deploy:
  provider: releases
  api_key:
    secure: a7qr+kngIipW0RSdIpdoZS3YzxdYOxsMyleYl8tOUFH5PJxg0gzxyp9UHmppP9widlFy3uWPSLrGpeKYQBF6rm0qPDJJ73oxO6CNI7GvxTirMS2Z83azJH6lWMrbSdK+hlIGcr6yA4rj60ccDPt9gLwUfN0+S8QKAvXrLfw+fkgschdZD32H+o4EAJLcF81olIaGzqb+ED8hQBqL5lujsMWqWuvL5LW3+ENrlMzvRqBCr0ZDSW7RUN0JCuBip5S/yzS0Un/RZkYgnuYQO/6EIrDp74d92dXxpQPOGayFRHum1DlXGZrRLmqX75nKmyQxRTMEZRxkEXk1sNovaocXDOan3K/huEPxpK2Jxs/+K+uQtAjocf+a53hDDLgBObsRU2fOxhu3j2J6XbF/iBz3+D8hUdDvJ6T8HSX5PQBAz5EWyHLrTkiSm/gyvEfb43rxbsanTwu5wPdZxgpRLzB8dbzlWJEHp0KScgmtzEUwVaOciWxbBFYcSo/ZoZ6M3eQYR0dmzd/oWxX1dr8qaa7WFfq6ihWfUX5WoTdWOGFbELPefYb4odeKeAzOYrOIqwGXSNht9s1UoqVKg5JKiboEbjGeBKw7+OtEgvdTJLTBFVruQSvurWtBEjKxShpQmKNSuLtWpYGejPT/a6Y8nY0w44KZItixRRN3R/TnsVQxQSw=
  file_glob:    true
  file:         ./pac-mule-*.tar.gz
  skip_cleanup: true
  on:
    branch:     master
    go:         "1.10.1"
    tags:       true
    repo:       junland/pac-mule
